spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: using
    url: jdbc:mysql://119.23.28.6:3306/using?useSSL=false
    username: root
    password: 12345679

server:
  port: 8080
  address: 0.0.0.0
  servlet:
    context-path: /
    session:
      timeout: 1800s
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: tk.mapper.model
  check-config-location: true
  config-location: classpath:mybatis-config.xml